name: dice_roller
description: A dice rolling game
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/dice1.png
    - assets/images/dice2.png
    - assets/images/dice3.png
    - assets/images/dice4.png
    - assets/images/dice5.png
    - assets/images/dice6.png